name: Build and deploy ASP.Net Core app to an Azure Web App - KineticChatBotAPI

env:
  AZURE_WEBAPP_NAME: app-smartleadsapi-test-sea
  AZURE_WEBAPP_PACKAGE_PATH: './dist'     
  DOTNET_VERSION: '8.0'                

on:
  push:
    branches: 
      - APP_STAGING
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v4
    
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build --configuration Release ./SmartLeadsPortalDotNetApi/SmartLeadsPortalDotNetApi.csproj

      - name: dotnet publish
        run: dotnet publish -c Release ./SmartLeadsPortalDotNetApi/SmartLeadsPortalDotNetApi.csproj -o ${{env.DOTNET_ROOT}}/dist
    
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
          package: ${{env.DOTNET_ROOT}}/dist
